import NAMASTE_NODE_SEASON_2_EPISODE_1 from "../NAMASTE_NODE_SE02_EP01.md?raw";
import NAMASTE_NODE_SEASON_2_EPISODE_2 from "../NAMASTE_NODE_SE02_EP02.md?raw";
import NAMASTE_NODE_SEASON_2_EPISODE_3 from "../NAMASTE_NODE_SE02_EP03.md?raw";
import NAMASTE_NODE_SEASON_2_EPISODE_4 from "../NAMASTE_NODE_SE02_EP04.md?raw";
import NAMASTE_NODE_SEASON_2_EPISODE_5 from "../NAMASTE_NODE_SE02_EP05.md?raw";
import NAMASTE_NODE_SEASON_2_EPISODE_6 from "../NAMASTE_NODE_SE02_EP06.md?raw";
import NAMASTE_NODE_SEASON_2_EPISODE_7 from "../NAMASTE_NODE_SE02_EP07.md?raw";

export const readmeMap = {
  namaste_node: {
    season_2: {
      episode_1: NAMASTE_NODE_SEASON_2_EPISODE_1,
      episode_2: NAMASTE_NODE_SEASON_2_EPISODE_2,
      episode_3: NAMASTE_NODE_SEASON_2_EPISODE_3,
      episode_4: NAMASTE_NODE_SEASON_2_EPISODE_4,
      episode_5: NAMASTE_NODE_SEASON_2_EPISODE_5,
      episode_6: NAMASTE_NODE_SEASON_2_EPISODE_6,
      episode_7: NAMASTE_NODE_SEASON_2_EPISODE_7,
    },
  },
};
